# Generated by Django 4.0.3 on 2022-04-06 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('to_send', models.EmailField(max_length=254, verbose_name='Адресат')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('send_date', models.DateTimeField(default=datetime.datetime(2022, 4, 6, 13, 43, 58, 272171), verbose_name='Дата отправки')),
                ('status', models.BooleanField(default=False, verbose_name='Статус отправки')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Новости и статьи', 'verbose_name_plural': 'Новости и статьи'},
        ),
    ]
