# Generated by Django 4.0.3 on 2022-04-06 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_emailmessage_alter_note_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='send_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отправки'),
        ),
    ]
